export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_FAIL = "GET_ADDRESS_FAIL";

export const GET_ADDRESS_BY_ID_REQUEST = "GET_ADDRESS_BY_ID_REQUEST";
export const GET_ADDRESS_BY_ID_SUCCESS = "GET_ADDRESS_BY_ID_SUCCESS";
export const GET_ADDRESS_BY_ID_FAIL = "GET_ADDRESS_BY_ID_FAIL";

export const NEW_ADDRESS_REQUEST = "NEW_ADDRESS_REQUEST";
export const NEW_ADDRESS_SUCCESS = "NEW_ADDRESS_SUCCESS";
export const NEW_ADDRESS_RESET = "NEW_ADDRESS_RESET";
export const NEW_ADDRESS_FAIL = "NEW_ADDRESS_FAIL";

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_RESET = "UPDATE_ADDRESS_RESET";
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_RESET = "DELETE_ADDRESS_RESET";
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL";

export const CLEAR_ADDRESS_ERRORS = "CLEAR_ADDRESS_ERRORS";