export const NEW_ORDER_REQUEST = "NEW_ORDER_REQUEST";
export const NEW_ORDER_SUCCESS = "NEW_ORDER_SUCCESS";
export const NEW_ORDER_FAIL = "NEW_ORDER_FAIL";

export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const PAYMENT_ADD_REQUEST = "PAYMENT_ADD_REQUEST";
export const PAYMENT_ADD_SUCCESS = "PAYMENT_ADD_SUCCESS";
export const PAYMENT_ADD_FAIL = "PAYMENT_ADD_FAIL";

export const CLEAR_ORDER_ERRORS = "CLEAR_ORDER_ERRORS";