export const GET_WISHLIST_REQUEST = "GET_WISHLIST_REQUEST";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_ERROR = "GET_WISHLIST_ERROR";
export const GET_WISHLIST_RESET = "GET_WISHLIST_RESET";

export const ADD_WISHLIST_REQUEST = "ADD_WISHLIST_REQUEST";
export const ADD_WISHLIST_SUCCESS = "ADD_WISHLIST_SUCCESS";
export const ADD_WISHLIST_ERROR = "ADD_WISHLIST_ERROR";
export const ADD_WISHLIST_RESET = "ADD_WISHLIST_RESET";

export const REMOVE_WISHLIST_REQUEST = "REMOVE_WISHLIST_REQUEST";
export const REMOVE_WISHLIST_SUCCESS = "REMOVE_WISHLIST_SUCCESS";
export const REMOVE_WISHLIST_FAIL = "REMOVE_WISHLIST_FAIL";
export const REMOVE_WISHLIST_RESET = "REMOVE_WISHLIST_RESET";

export const CLEAR_WISHLIST_ERRORS = "CLEAR_WISHLIST_ERRORS";